[package]
name = "storyarchive"
version = "0.1.0"
authors = ["Txuritan <txurtian@yahoo.com>"]

[dependencies]
config = "0.8"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
serde = "1.0"
serde_derive = "1.0"
